### ISSUE TITLE
Can't individually stop downloads

### ISSUE THREAD

**Issue by Zenivo** [WebcamDownloader/WebcamDownloader#1]
I do not know if this is a limitation of how the download works, but right now if you run multiple downloads simulatenously, you can only stop them all at the same time. It would be nice of you could only stop one of the downloads.

**Comment by WebcamDownloader** [comment]
You can untick the checkbox and press the Download button again, it will apply the changes, I probably need to rename it.

**Comment by WebcamDownloader** [comment]
@Zenivo Please let me know if I can close this issue.

**Comment by Zenivo** [comment]
Yes, sorry my bad. I'm not that familiar with using Github.
