### ISSUE TITLE
Changed playlist url for stripchat

### ISSUE THREAD

**Issue by aitschti** [WebcamDownloader/WebcamDownloader#11]
First of all, great tool!

Stripchat changed their CDN, so please change line 58 in your _stripchathost.cpp_ to

`auto streamUrl = QString("https://b-%1.doppiocdn.com/hls/%2/%2.m3u8")`

or alternatively to

`auto streamUrl = QString("https://b-%1.doppiocdn.com/hls/%2/master_%2.m3u8")`

This should fix stream recording.

Sorry for not using a pull request, need to figure this out another time. ;)

Cheers

**Comment by WebcamDownloader** [comment]
Thanks, fixed and will be released shortly!
