### ISSUE TITLE
Videos output very choppy

### ISSUE THREAD

**Issue by sirmiles42** [WebcamDownloader/WebcamDownloader#14]
Hi there, I'd like to report a problem that I've been encountered that the output video is very choppy and even having lots and lots of frame skip. I try looking for the solution and I should encode it into .mp4 file format but it doesn't really solve the problems. It feels like to run smoothly but doesn't change the fact that it still has a lot of missing frames and even audio delay. Thanks.

**Comment by WebcamDownloader** [comment]
I can't reproduce the issue. Feel free to reopen if you can provide more details.
