### ISSUE TITLE
Stripchat download not working anymore

### ISSUE THREAD

**Issue by koralaa123** [WebcamDownloader/WebcamDownloader#16]
For some reason, the stripchat download does not work anymore.

**Comment by adithyag1988** [comment]
Same issue.

**Comment by 22Gremlins** [comment]
Same for me also hope it can be fixed as this is a very good program and was working great.

**Comment by koralaa123** [comment]
It works again, maybe sc changed something in the back end.

**Comment by 22Gremlins** [comment]
Yes I noticed it started working again, thanks for the update and the
excellent program.
