### ISSUE TITLE
Application closes after random amount of time causing duplicates of streams.

### ISSUE THREAD

**Issue by SamuraiThomas** [WebcamDownloader/WebcamDownloader#3]
The app randomy closes. Once it closes, it doesn't look for new streams, and the currently recording streams continue recording until the user stops streaming. Therefore, upon re-opening the app, all online streams begin recording again, and the online user's streams begin downloading AGAIN. Any streams that were previously running continue, and a new set of streams begin recording so therefore i could be downloading the same stream twice.

**Comment by WebcamDownloader** [comment]
I'm unable to reproduce this issue, do you have any more details that could lead to the source of the crashes?
