### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by mrpickless666** [WebcamDownloader/WebcamDownloader#6]
As of today the recorder just stopped working. The performers are online but it refuses to record either manual or auto recordings.

**Comment by WebcamDownloader** [comment]
I will look into it.

**Comment by WebcamDownloader** [comment]
Fixed it, will release the new version in few minutes.

**Comment by pench224** [comment]
Stopped working again

**Comment by WebcamDownloader** [comment]
@pench224 Just tested it, seems to be working fine. Please open a new issue with more description of the error behavior.
