### ISSUE TITLE
scrolling

### ISSUE THREAD

**Issue by bublich** [WebcamDownloader/WebcamDownloader#7]
Good day.
Is it possible to scroll the links below after filling the window? After adding the link, the bottom links will be scrolled and not visible.
Thank you for a great program.

**Comment by WebcamDownloader** [comment]
Hello, this is a bug, thanks for the report, I will look into it as soon as I have time. For now try maximizing the window.

**Comment by bublich** [comment]
Unfortunately the same result. I've tried it several times before. The maximum visible number of links is 32.WIN10 x64.Opera 79.0.4143.72.
Thanks.

**Comment by WebcamDownloader** [comment]
Fixed in new version 0.4.0 ([download here](https://github.com/WebcamDownloader/WebcamDownloader/releases/tag/v0.4.0))

**Comment by bublich** [comment]
Thank you for everyone, it works perfectly.
