### ISSUE TITLE
Unsupported file Ubuntu installation

### ISSUE THREAD

**Issue by Harnald** [WebcamDownloader/WebcamDownloader#8]
i'm not able to install on ubuntu

**Comment by WebcamDownloader** [comment]
Which file are you trying to run and which Ubuntu version do you have?

**Comment by Harnald** [comment]
i tried the gui on 20.04

**Comment by WebcamDownloader** [comment]
And what error are you getting? I just span up a new virtual machine and it complained about some missing library, try this:

`sudo apt-get -y install libxcb-xinerama0 ffmpeg`

This will install the missing library and ffmpeg which is used to download files.

**Comment by WebcamDownloader** [comment]
Did it help?
